version: "3.9"
services:
  checker:
    depends_on:
      calendar:
        condition: service_healthy
    image: hw15_checker_prod
    container_name: hw15_checker_prod
    hostname: checker
    build:
      context: ../.
      args:
        MICROSERVICE: checker
        CONFIG_FILE: checker.yaml
      dockerfile: ./docker/Dockerfile
    networks:
      private:
      public:
