run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  gosec:
    excludes:
      - G114
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - 'hw12_13_14_15_calendar/internal/interfaces'
          - 'hw12_13_14_15_calendar/internal/logger'
          - 'hw12_13_14_15_calendar/internal/models'
          - 'hw12_13_14_15_calendar/internal/storage/pgsqldtb'
          - 'hw12_13_14_15_calendar/internal/storage/gomemory'
          - 'github.com/lib/pq'
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/icrowley
          - 'hw12_13_14_15_calendar/internal/interfaces'
          - 'hw12_13_14_15_calendar/internal/logger'
          - 'hw12_13_14_15_calendar/internal/models'
          - 'hw12_13_14_15_calendar/internal/storage/pgsqldtb'
          - 'hw12_13_14_15_calendar/internal/storage/gomemory'
          - 'github.com/lib/pq'
  # funlen:
  # lines: 200
  # statements: 120

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
