Source: 
  DSN: "amqp://guest:guest@localhost:5672/"
  QueueName: q_events_for_notify
  GetbackToExchangeName: exch_events
  GetbackKey: notify
Target:
  DSN: "amqp://guest:guest@localhost:5672/"
  ExchangeName: "exch_events"
  RoutingKey: archive
TimeoutSec: 0
log:
  level: INFO
 