http: 
  host: 0.0.0.0
  port: 8080
  readtimeout: "5s"
  readheadertimeout: "5s"
  writetimeout: "5s"
  maxheaderbytes: 1048576
rpc: 
  host: 0.0.0.0
  port: 5000
storage:
  type: pgsqldtb
  dsn: "user=hw15user password=hw15user host='127.0.0.1' database=hw15calendar search_path=hw15calendar"
log:
  level: INFO
 