HTTP:
  Host: 172.40.0.1
  Port: 8888
Storage:
  Type: pgsqldtb
  DSN: "user=hw15user password=hw15user host=hw15_postgres_integration_test port=5432 database=hw15 search_path=hw15calendar sslmode=disable"
Sended:
  DSN: "amqp://hw15user:hw15user@hw15_rabbitmq_integration_test:5672/"
  QueueName: "q_noticies_send"
Archived:
  DSN: "amqp://hw15user:hw15user@hw15_rabbitmq_integration_test:5672/"
  QueueName: "q_noticies_archived"
Log:
  Level: INFO
Counts:
  Send: 10
  Archive: 10
  Defer: 10