http: 
  host: 172.20.0.1
  port: 8888
storage:
  type: pgsqldtb
	dsn: "user=hw15user password=hw15user host='hw15_postgres_prod' database=hw15 search_path=hw15calendar"
sended:
	dsn: "amqp://hw15user:hw15user@hw15_rabbitmq_prod:5672/"
  queuename: "q_noticies_send"
archived:
	dsn: "amqp://hw15user:hw15user@hw15_rabbitmq_prod:5672/"
  queuename: "q_noticies_archived"
