rabbitmq: 
  dsn: "amqp://hw15user:hw15user@hw15_rabbitmq_integration_test:5672/"
  exchanges: [
    { 
      name: notice_exchange, 
      bindings : [
        { 
          BindQueue: q_unspecified, 
          BindKey:  
        },
        { 
          BindQueue: q_noticies_sheduled, 
          BindKey: shedule 
        },
        { 
          BindQueue: q_noticies_archived, 
          BindKey: archive 
        },
        { 
          BindQueue: q_noticies_archived, 
          BindKey: send 
        },
        { 
          BindQueue: q_noticies_send, 
          BindKey: send 
        },
      ]
    },
  ]
log:
  level: INFO
 