Source: 
  DSN: "amqp://guest:guest@172.18.0.1:5672/"
  QueueName: "q_noticies_sheduled"
  GetbackToExchangeName: notice_exchange
  GetbackKey: shedule
Target:
  DSN: "amqp://guest:guest@172.18.0.1:5672/"
  ExchangeName: "notice_exchange"
  RoutingKey: send
TimeoutSec: 3
log:
  level: INFO
 