Source: 
  DSN: "amqp://guest:guest@localhost:5672/"
  QueueName: "q_events_for_notify"
Target:
  dsn: "amqp://guest:guest@localhost:5672/"
  ExchangeName: "exch_events"
  RoutingKey: 
    - "send"
    - "archive"
TimeoutSec: 5
log:
  level: INFO
 